# Generated by Django 4.2.2 on 2023-07-21 02:38

from django.db import migrations, models
import ui.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default='0123456789', max_length=10, validators=[ui.models.validate_digit_length], verbose_name='Code')),
            ],
        ),
    ]
